baseURL = 'https://prykhodchenkomykyta.github.io/'
languageCode = 'en-us'
title = 'Blog'

paginate = 4

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"
